on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/src'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.15.3
        env:
          PAGES_BRANCH: master
          TOKEN: ${{ secrets.ZOLA_TOKEN }}
