on: push
name: Build and deploy on push
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install zola
        run: |
          wget -q -O - \
          "https://github.com/getzola/zola/releases/download/v0.15.2/zola-v0.15.2-x86_64-unknown-linux-gnu.tar.gz" \
          | sudo tar xzf - -C /usr/local/bin
      - name: Build
        run: zola build

      - name: Push
        run: |
          git checkout origin/master
          mv -f public/* .
          rmdir public
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add -A
          git commit -m "Automatic deploy"
          git push "https://maroider:${{ secrets.ZOLA_TOKEN }}@github.com/maroider/maroider.github.io.git" master:master
